### PR TITLE
Polymer 3 Conversion

### PR DESCRIPTION
**Pull request by svanherk**
The modulizer was run off the changes in https://github.com/BrightspaceUI/hierarchical-view/pull/31, that should be merged first and a `hybrid` branch created.

### CODE REVIEW

**Comment by svanherk** [comment]
@qwangd2l

**Comment by qwangd2l** [comment]
Tested in safari and it works fine.

**Comment by svanherk** [comment]
Was there anything else from https://github.com/BrightspaceUI/hierarchical-view/pull/31 to be addressed or is this good to go?  I believe the font difference is an issue with `typography` that @margaree is looking into.  The fix will be a patch release and all the other repos we've converted will get it "for free" once it's in.

**Comment by qwangd2l** [comment]
> Was there anything else from #31 to be addressed or is this good to go? I believe the font difference is an issue with `typography` that @margaree is looking into. The fix will be a patch release and all the other repos we've converted will get it "for free" once it's in.

Dave did mention that there's empty lines in: https://github.com/BrightspaceUI/hierarchical-view/pull/34/files#diff-67a76aee200520099d05bf6b598242b3R32
(discussion: https://github.com/BrightspaceUI/hierarchical-view/pull/31#discussion_r232818532)

If it's not that big of a deal (since lint tests still pass), I believe this is good to go.

**Comment by svanherk** [comment]
Ah darn, wished I'd caught that during my other upgrades.  We have `strip-whitespace` in there now at least, so that should help.

**Pull request merged**
